<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Asset;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Asset::create(["name" => "Headset Sheila", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2012-08-04", "state" => 2, "specification" => "Non adipisci non quas quas.", "location" => "HN"]);
        Asset::create(["name" => "Bluetooth Mouse Alexander", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-05-25", "state" => -1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Headset Orpha", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2014-07-20", "state" => -1, "specification" => "Ullam veritatis quas nihil et reiciendis eius.", "location" => "HN"]);
        Asset::create(["name" => "Bluetooth Mouse Santina", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2022-01-05", "state" => 2, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Laptop Lucinda", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-04-04", "state" => -2, "specification" => "Eius ex laborum ipsam corporis ut recusandae voluptatem.", "location" => "HCM"]);
        Asset::create(["name" => "Laptop Harmon", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-08-26", "state" => -2, "specification" => "Occaecati qui tempora debitis.", "location" => "HCM"]);
        Asset::create(["name" => "Laptop Mckenzie", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-12-22", "state" => -1, "specification" => "", "location" => "HCM"]);
        Asset::create(["name" => "PC Jacinto", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2015-12-21", "state" => 0, "specification" => "Eum et quia quos consequatur qui voluptates quae.", "location" => "HN"]);
        Asset::create(["name" => "Monitor Novella", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2015-11-13", "state" => 2, "specification" => "Quia aperiam rerum et dolor error omnis eos ab.", "location" => "DN"]);
        Asset::create(["name" => "Bluetooth Mouse Johan", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-02-19", "state" => -2, "specification" => "Occaecati eveniet inventore ipsam explicabo.", "location" => "HCM"]);
        Asset::create(["name" => "Bluetooth Mouse Carlo", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-08-17", "state" => 0, "specification" => "", "location" => "HCM"]);
        Asset::create(["name" => "Bluetooth Mouse Shany", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2015-06-19", "state" => -2, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "PC Dolly", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2019-01-24", "state" => 0, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Bluetooth Mouse Stefanie", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2021-09-06", "state" => 0, "specification" => "Exercitationem et sed rerum voluptatem reiciendis veniam.", "location" => "HN"]);
        Asset::create(["name" => "Headset Alana", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-10-20", "state" => -1, "specification" => "Totam non quia doloribus alias et dolores consectetur assumenda.", "location" => "HCM"]);
        Asset::create(["name" => "Laptop Barry", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2012-10-01", "state" => 0, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Headset Olin", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2021-08-22", "state" => 1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Bluetooth Mouse Nya", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2012-11-30", "state" => 0, "specification" => "Et et ullam dolores repellendus temporibus.", "location" => "DN"]);
        Asset::create(["name" => "Monitor Norene", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2019-05-25", "state" => -1, "specification" => "", "location" => "HCM"]);
        Asset::create(["name" => "Bluetooth Mouse Yvette", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2012-09-05", "state" => 1, "specification" => "Quidem id recusandae fugiat commodi eos quia iure.", "location" => "HCM"]);
        Asset::create(["name" => "Headset Alfonso", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-06-07", "state" => 2, "specification" => "", "location" => "HCM"]);
        Asset::create(["name" => "Bluetooth Mouse Sunny", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2019-01-21", "state" => -2, "specification" => "Illo mollitia commodi voluptas iusto saepe omnis repudiandae blanditiis.", "location" => "HN"]);
        Asset::create(["name" => "PC Wiley", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-03-09", "state" => 1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "PC Norene", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2015-07-05", "state" => -1, "specification" => "Ducimus possimus itaque optio et.", "location" => "HN"]);
        Asset::create(["name" => "PC Buddy", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2019-07-06", "state" => 1, "specification" => "Vel rem et voluptatum molestiae deleniti modi.", "location" => "HN"]);
        Asset::create(["name" => "PC Avery", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-11-29", "state" => 2, "specification" => "", "location" => "HCM"]);
        Asset::create(["name" => "Headset Price", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-02-28", "state" => 1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Monitor Pedro", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2022-01-14", "state" => 2, "specification" => "Nihil asperiores perferendis reiciendis ab voluptatem iste.", "location" => "HN"]);
        Asset::create(["name" => "Monitor Eula", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2016-09-06", "state" => 1, "specification" => "Quis et iste et voluptate eaque.", "location" => "HN"]);
        Asset::create(["name" => "Bluetooth Mouse Demetris", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-07-17", "state" => -1, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "PC Fleta", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2016-07-20", "state" => -2, "specification" => "Error nobis animi ab ut quasi.", "location" => "HCM"]);
        Asset::create(["name" => "Bluetooth Mouse Adrain", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-03-12", "state" => 2, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Laptop Brandon", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-08-08", "state" => 0, "specification" => "Architecto exercitationem aut qui quaerat harum qui.", "location" => "HCM"]);
        Asset::create(["name" => "Headset Hector", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2016-10-30", "state" => -2, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Laptop Misael", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2014-10-01", "state" => 1, "specification" => "Repudiandae dignissimos ut ratione quia esse assumenda consequatur sed delectus.", "location" => "HN"]);
        Asset::create(["name" => "Laptop Elyse", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-01-20", "state" => 2, "specification" => "Quisquam impedit sint modi possimus.", "location" => "DN"]);
        Asset::create(["name" => "Bluetooth Mouse Kristian", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-07-03", "state" => 1, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Laptop Urban", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-01-17", "state" => 2, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Headset Nona", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2019-06-10", "state" => 1, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Laptop Asa", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-07-02", "state" => 0, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Headset Roberta", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2021-07-23", "state" => 0, "specification" => "Est voluptate dolor veritatis laborum.", "location" => "DN"]);
        Asset::create(["name" => "Bluetooth Mouse Ari", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2017-10-28", "state" => 1, "specification" => "Quo ea ex harum quis optio.", "location" => "HN"]);
        Asset::create(["name" => "Laptop Stuart", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-11-25", "state" => 1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Laptop Brad", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2015-07-07", "state" => -1, "specification" => "Occaecati corrupti maiores in numquam quam sequi nam consequuntur.", "location" => "HCM"]);
        Asset::create(["name" => "Laptop Florine", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2021-10-07", "state" => -1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "PC Molly", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-12-15", "state" => 2, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Laptop Larissa", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-12-27", "state" => 1, "specification" => "Natus vel sint sit.", "location" => "HCM"]);
        Asset::create(["name" => "PC Mollie", "category_id" => $category_id = "BM", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-07-15", "state" => 2, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Bluetooth Mouse Reinhold", "category_id" => $category_id = "LP", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2018-05-14", "state" => 2, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Bluetooth Mouse Peggie", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2019-06-18", "state" => -1, "specification" => "", "location" => "DN"]);
        Asset::create(["name" => "Bluetooth Mouse Mckayla", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2022-03-22", "state" => -2, "specification" => "Maiores numquam aut dolores omnis nobis voluptas sed.", "location" => "HN"]);
        Asset::create(["name" => "PC Darlene", "category_id" => $category_id = "MO", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2020-12-26", "state" => 2, "specification" => "", "location" => "HN"]);
        Asset::create(["name" => "Monitor Jettie", "category_id" => $category_id = "PC", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2013-03-29", "state" => -1, "specification" => "", "location" => "HCM"]);
        Asset::create(["name" => "Laptop Barton", "category_id" => $category_id = "HE", "asset_code" => $category_id . str_pad(Asset::max('id') + 1, 6, "0", STR_PAD_LEFT), "installed_date" => "2016-10-15", "state" => -1, "specification" => "Velit aspernatur eveniet dolorum ea veritatis.", "location" => "HN"]);
    }
}
