<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Foundation\Testing\RefreshDatabase;


class UserSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::create(["first_name" => "an", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "le binh", "date_of_birth" => "1980-07-23", "joined_date" => "2005-12-30", "username" => "anlb", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => null, "location" => "HN"]);
        User::create(["first_name" => "diep", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen thi ngoc", "date_of_birth" => "1979-01-09", "joined_date" => "2015-11-14", "username" => "diepntn", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => 0, "location" => "HN"]);
        User::create(["first_name" => "duong", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "lam tran tung", "date_of_birth" => "1973-08-25", "joined_date" => "2008-03-20", "username" => "duongltt", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => 1, "location" => "HCM"]);
        User::create(["first_name" => "duc", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen anh", "date_of_birth" => "2001-08-03", "joined_date" => "2021-10-24", "username" => "ducna", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => null, "location" => "HN"]);
        User::create(["first_name" => "hai", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "le cong", "date_of_birth" => "1996-08-22", "joined_date" => "2017-10-21", "username" => "hailc", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 1, "location" => "HN"]);
        User::create(["first_name" => "hao", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen", "date_of_birth" => "1976-04-21", "joined_date" => "2007-07-05", "username" => "haon", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "huy", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "mai gia", "date_of_birth" => "1979-11-29", "joined_date" => "2009-02-14", "username" => "huymg", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => 0, "location" => "DN"]);
        User::create(["first_name" => "nhu", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen ho quynh ", "date_of_birth" => "2001-04-27", "joined_date" => "2021-11-28", "username" => "nhunhq", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "phuc", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen hoang", "date_of_birth" => "1990-02-05", "joined_date" => "2018-12-21", "username" => "phucnh", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => 1, "location" => "HN"]);
        User::create(["first_name" => "thinh", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen huu", "date_of_birth" => "1997-03-21", "joined_date" => "2020-08-01", "username" => "thinhnh", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "thy", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen ngoc xuan", "date_of_birth" => "1981-10-30", "joined_date" => "2011-10-14", "username" => "thynnx", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => 0, "location" => "HCM"]);
        User::create(["first_name" => "tri", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen minh", "date_of_birth" => "2001-05-17", "joined_date" => "2022-04-02", "username" => "trinm", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 1, "location" => "HN"]);
        User::create(["first_name" => "tuan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "duong duc", "date_of_birth" => "1995-12-13", "joined_date" => "2016-04-19", "username" => "tuandd", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "tuan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen lam", "date_of_birth" => "1979-03-29", "joined_date" => "2015-12-12", "username" => "tuannl", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "vy", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen khanh", "date_of_birth" => "1986-02-06", "joined_date" => "2010-12-12", "username" => "vynk", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => 0, "location" => "HN"]);
        User::create(["first_name" => "nam", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "vu gia", "date_of_birth" => "1984-02-05", "joined_date" => "2016-01-26", "username" => "namvg", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "phong", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen toan", "date_of_birth" => "1971-02-20", "joined_date" => "2006-03-12", "username" => "phongnt", "password" => bcrypt(12345), "admin" => TRUE, "state" => 0, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "tin", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "ho trong", "date_of_birth" => "1988-09-22", "joined_date" => "2017-03-16", "username" => "tinht", "password" => bcrypt(12345), "admin" => FALSE, "state" => -1, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "truc", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "le nguyen trung", "date_of_birth" => "1995-01-27", "joined_date" => "2016-11-27", "username" => "truclnt", "password" => bcrypt(12345), "admin" => TRUE, "state" => 0, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "bich", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "vo hoa thi", "date_of_birth" => "1999-10-16", "joined_date" => "2022-04-16", "username" => "bichvht", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => 0, "location" => "HCM"]);
        User::create(["first_name" => "hong", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "pham thi", "date_of_birth" => "1983-02-28", "joined_date" => "2016-08-31", "username" => "hongpt", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 0, "location" => "HCM"]);
        User::create(["first_name" => "lam", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen van tung", "date_of_birth" => "1971-03-03", "joined_date" => "2008-12-11", "username" => "lamnvt", "password" => bcrypt(12345), "admin" => FALSE, "state" => -1, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "anh", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen thi", "date_of_birth" => "1980-01-03", "joined_date" => "2017-04-14", "username" => "anhnt", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 0, "location" => "HCM"]);
        User::create(["first_name" => "dat", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "duong ngoc", "date_of_birth" => "1994-02-04", "joined_date" => "2020-11-14", "username" => "datdn", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "hieu", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen manh", "date_of_birth" => "1971-01-29", "joined_date" => "2016-05-21", "username" => "hieunm", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "kien", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "ho trung", "date_of_birth" => "1986-12-18", "joined_date" => "2018-07-31", "username" => "kienht", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "phuong", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "hoang quy", "date_of_birth" => "1989-04-19", "joined_date" => "2018-01-11", "username" => "phuonghq", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => null, "location" => "HN"]);
        User::create(["first_name" => "son", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen khac", "date_of_birth" => "1979-10-20", "joined_date" => "2001-12-04", "username" => "sonnk", "password" => bcrypt(12345), "admin" => TRUE, "state" => 0, "gender" => 1, "location" => "HCM"]);
        User::create(["first_name" => "tuan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen van", "date_of_birth" => "1999-01-22", "joined_date" => "2019-11-06", "username" => "tuannv", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => null, "location" => "HN"]);
        User::create(["first_name" => "hien", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "pham ngoc", "date_of_birth" => "1981-07-16", "joined_date" => "2007-03-02", "username" => "hienpn", "password" => bcrypt(12345), "admin" => FALSE, "state" => -1, "gender" => 0, "location" => "DN"]);
        User::create(["first_name" => "minh", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "hoang anh", "date_of_birth" => "1987-08-09", "joined_date" => "2018-07-07", "username" => "minhha", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => null, "location" => "HN"]);
        User::create(["first_name" => "nhung", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "dinh thi hong", "date_of_birth" => "1994-07-29", "joined_date" => "2022-06-19", "username" => "nhungdth", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "tuan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen cong", "date_of_birth" => "1973-12-13", "joined_date" => "2005-08-19", "username" => "tuannc", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "anh", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "dinh cuong", "date_of_birth" => "1977-10-27", "joined_date" => "2007-12-04", "username" => "anhdc", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "anh", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "pham phuong", "date_of_birth" => "1987-02-12", "joined_date" => "2016-07-30", "username" => "anhpp", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 1, "location" => "HN"]);
        User::create(["first_name" => "duy", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "vu manh", "date_of_birth" => "1997-03-09", "joined_date" => "2018-04-29", "username" => "duyvm", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => null, "location" => "HN"]);
        User::create(["first_name" => "kien", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "vu van", "date_of_birth" => "1978-03-13", "joined_date" => "2004-06-20", "username" => "kienvv", "password" => bcrypt(12345), "admin" => TRUE, "state" => 0, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "tuan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "dang cong", "date_of_birth" => "1971-03-22", "joined_date" => "2013-05-23", "username" => "tuandc", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "tuan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "phung anh", "date_of_birth" => "1981-06-20", "joined_date" => "2013-01-06", "username" => "tuanpa", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 0, "location" => "DN"]);
        User::create(["first_name" => "dat", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "dao trung", "date_of_birth" => "1972-12-16", "joined_date" => "2021-11-21", "username" => "datdt", "password" => bcrypt(12345), "admin" => FALSE, "state" => -1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "tiep", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "bui quang", "date_of_birth" => "1990-03-08", "joined_date" => "2014-10-19", "username" => "tiepbq", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "dung", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "vu anh", "date_of_birth" => "1983-07-28", "joined_date" => "2010-06-23", "username" => "dungva", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => 1, "location" => "HN"]);
        User::create(["first_name" => "hung", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "le duy", "date_of_birth" => "1979-11-16", "joined_date" => "2017-05-14", "username" => "hungld", "password" => bcrypt(12345), "admin" => TRUE, "state" => 0, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "nam", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "giap van", "date_of_birth" => "1994-01-21", "joined_date" => "2020-08-16", "username" => "namgv", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => 1, "location" => "DN"]);
        User::create(["first_name" => "thanh", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen trung", "date_of_birth" => "1993-11-16", "joined_date" => "2015-02-01", "username" => "thanhnt", "password" => bcrypt(12345), "admin" => FALSE, "state" => -1, "gender" => null, "location" => "DN"]);
        User::create(["first_name" => "thao", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "tran thi", "date_of_birth" => "1970-06-22", "joined_date" => "1991-12-06", "username" => "thaott", "password" => bcrypt(12345), "admin" => FALSE, "state" => 1, "gender" => 0, "location" => "HN"]);
        User::create(["first_name" => "ngoan", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "tran thi", "date_of_birth" => "1976-05-25", "joined_date" => "1999-04-27", "username" => "ngoantt", "password" => bcrypt(12345), "admin" => TRUE, "state" => -1, "gender" => 0, "location" => "HN"]);
        User::create(["first_name" => "quang", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen le minh", "date_of_birth" => "1992-01-11", "joined_date" => "2014-10-09", "username" => "quangnlm", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "bac", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "le van", "date_of_birth" => "1978-10-23", "joined_date" => "2017-08-26", "username" => "baclv", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => 1, "location" => "HCM"]);
        User::create(["first_name" => "huy", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "nguyen quang", "date_of_birth" => "1978-09-30", "joined_date" => "2019-06-27", "username" => "huynq", "password" => bcrypt(12345), "admin" => FALSE, "state" => 0, "gender" => null, "location" => "HCM"]);
        User::create(["first_name" => "quy", "staff_code" => "SD" . str_pad(User::max('id') + 1, 4, "0", STR_PAD_LEFT), "last_name" => "truong cong", "date_of_birth" => "2001-12-26", "joined_date" => "2022-07-14", "username" => "quytc", "password" => bcrypt(12345), "admin" => TRUE, "state" => 1, "gender" => null, "location" => "HN"]);
    }
}
