export const userConstants = {
    GET_USER_INFO: 'GET_USER_INFO',
    GET_USER_EDIT: 'GET_USER_EDIT',
    GET_USER_CREATE: 'GET_USER_CREATE',
    GET_ASSET_INFO: 'GET_ASSET_INFO',
    GET_ASSET_EDIT: 'GET_ASSET_EDIT'
}
